#ifndef PLATFORM_HPP
#define PLATFORM_HPP

// Platform macros
#define DOG_PLATFORM(X) DOG_PLATFORM_##X()
#define DOG_PLATFORM_UNIX() PLATFORM_UNIX
#define DOG_PLATFORM_WIN32() PLATFORM_WIN32
#define DOG_PLATFORM_APPLE() PLATFORM_APPLE

#endif
