#ifndef PLATFORM_HPP
#define PLATFORM_HPP

#define SEMPERVIRENS_PLATFORM(X) SEMPERVIRENS_PLATFORM_##X()
#define SEMPERVIRENS_PLATFORM_UNIX() PLATFORM_UNIX
#define SEMPERVIRENS_PLATFORM_WIN32() PLATFORM_WIN32
#define SEMPERVIRENS_PLATFORM_APPLE() PLATFORM_APPLE

#if SEMPERVIRENS_PLATFORM_WIN32()
  #define SEMPERVIRENS_IMPORT() __declspec(dllimport)
  #define SEMPERVIRENS_EXPORT() __declspec(dllexport)
#else
  #define SEMPERVIRENS_IMPORT()
  #define SEMPERVIRENS_EXPORT()
#endif


#endif
