#ifndef LINUXKEYCODES_HPP
#define LINUXKEYCODES_HPP

#define XK_LATIN1
#include <X11/keysymdef.h>

namespace sempervirens::input {

#define SEMPERVIRENS_SPACE XK_space 
#define SEMPERVIRENS_EXCLA XK_exclam                    
#define SEMPERVIRENS_QUOTE XK_quotedbl                  
#define SEMPERVIRENS_NSIGN XK_numbersign                
#define SEMPERVIRENS_USDLR XK_dollar                    
#define SEMPERVIRENS_PRCNT XK_percent                   
#define SEMPERVIRENS_AMPSD XK_ampersand                 
#define SEMPERVIRENS_APOST XK_apostrophe                
#define SEMPERVIRENS_QUOTR XK_quoteright                
#define SEMPERVIRENS_PARNL XK_parenleft                 
#define SEMPERVIRENS_PARNR XK_parenright                
#define SEMPERVIRENS_ASTER XK_asterisk                  
#define SEMPERVIRENS_PLUS XK_plus                      
#define SEMPERVIRENS_COMM XK_comma                     
#define SEMPERVIRENS_MINUS XK_minus                     
#define SEMPERVIRENS_POINT XK_period                    
#define SEMPERVIRENS_SLASH XK_slash                     
#define SEMPERVIRENS_0 XK_0                         
#define SEMPERVIRENS_1 XK_1                         
#define SEMPERVIRENS_2 XK_2                         
#define SEMPERVIRENS_3 XK_3                         
#define SEMPERVIRENS_4 XK_4                         
#define SEMPERVIRENS_5 XK_5                         
#define SEMPERVIRENS_6 XK_6                         
#define SEMPERVIRENS_7 XK_7                         
#define SEMPERVIRENS_8 XK_8                         
#define SEMPERVIRENS_9 XK_9                         
#define SEMPERVIRENS_COLON XK_colon                     
#define SEMPERVIRENS_SEMIC XK_semicolon                 
#define SEMPERVIRENS_LESS XK_less                      
#define SEMPERVIRENS_EQUAL XK_equal                     
#define SEMPERVIRENS_GREAT XK_greater                   
#define SEMPERVIRENS_QUEST XK_question                  
#define SEMPERVIRENS_AT XK_at                        
#define SEMPERVIRENS_A XK_A                         
#define SEMPERVIRENS_B XK_B                         
#define SEMPERVIRENS_C XK_C                         
#define SEMPERVIRENS_D XK_D                         
#define SEMPERVIRENS_E XK_E                         
#define SEMPERVIRENS_F XK_F                         
#define SEMPERVIRENS_G XK_G                         
#define SEMPERVIRENS_H XK_H                         
#define SEMPERVIRENS_I XK_I                         
#define SEMPERVIRENS_J XK_J                         
#define SEMPERVIRENS_K XK_K                         
#define SEMPERVIRENS_L XK_L                         
#define SEMPERVIRENS_M XK_M                         
#define SEMPERVIRENS_N XK_N                         
#define SEMPERVIRENS_O XK_O                         
#define SEMPERVIRENS_P XK_P                         
#define SEMPERVIRENS_Q XK_Q                         
#define SEMPERVIRENS_R XK_R                         
#define SEMPERVIRENS_S XK_S                         
#define SEMPERVIRENS_T XK_T                         
#define SEMPERVIRENS_U XK_U                         
#define SEMPERVIRENS_V XK_V                         
#define SEMPERVIRENS_W XK_W                         
#define SEMPERVIRENS_X XK_X                         
#define SEMPERVIRENS_Y XK_Y                         
#define SEMPERVIRENS_Z XK_Z                         
#define SEMPERVIRENS_BRACL XK_bracketleft               
#define SEMPERVIRENS_BKSLA XK_backslash                 
#define SEMPERVIRENS_BRACR XK_bracketright              
#define SEMPERVIRENS_CIRCM XK_asciicircum               
#define SEMPERVIRENS_UNDER XK_underscore                
#define SEMPERVIRENS_GRAVE XK_grave                     
#define SEMPERVIRENS_QUOTL XK_quoteleft                 
#define SEMPERVIRENS_a XK_a                         
#define SEMPERVIRENS_b XK_b                         
#define SEMPERVIRENS_c XK_c                         
#define SEMPERVIRENS_d XK_d                         
#define SEMPERVIRENS_e XK_e                         
#define SEMPERVIRENS_f XK_f                         
#define SEMPERVIRENS_g XK_g                         
#define SEMPERVIRENS_h XK_h                         
#define SEMPERVIRENS_i XK_i                         
#define SEMPERVIRENS_j XK_j                         
#define SEMPERVIRENS_k XK_k                         
#define SEMPERVIRENS_l XK_l                         
#define SEMPERVIRENS_m XK_m                         
#define SEMPERVIRENS_n XK_n                         
#define SEMPERVIRENS_o XK_o                         
#define SEMPERVIRENS_p XK_p                         
#define SEMPERVIRENS_q XK_q                         
#define SEMPERVIRENS_r XK_r                         
#define SEMPERVIRENS_s XK_s                         
#define SEMPERVIRENS_t XK_t                         
#define SEMPERVIRENS_u XK_u                         
#define SEMPERVIRENS_v XK_v                         
#define SEMPERVIRENS_w XK_w                         
#define SEMPERVIRENS_x XK_x                         
#define SEMPERVIRENS_y XK_y                         
#define SEMPERVIRENS_z XK_z                         
#define SEMPERVIRENS_CURLL XK_braceleft                 
#define SEMPERVIRENS_BAR XK_bar                       
#define SEMPERVIRENS_CURLR XK_braceright                
#define SEMPERVIRENS_TILDE XK_asciitilde                
}
#endif
